# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebViewInCellAdaptive' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  pod 'Masonry', '~> 1.1.0'

  # Pods for WebViewInCellAdaptive

  target 'WebViewInCellAdaptiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WebViewInCellAdaptiveUITests' do
    # Pods for testing
  end

end
